// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

package dev.sultanov.grpc.authentication.shared;

public interface GreetingResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dev.sultanov.grpc.authentication.shared.GreetingResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string greeting = 1;</code>
     */
    java.lang.String getGreeting();
    /**
     * <code>string greeting = 1;</code>
     */
    com.google.protobuf.ByteString
    getGreetingBytes();
}
