// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

package dev.sultanov.grpc.authentication.shared;

public final class GreetingServiceOuterClass {
    private GreetingServiceOuterClass() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_sultanov_grpc_authentication_shared_GreetingRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_dev_sultanov_grpc_authentication_shared_GreetingRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_sultanov_grpc_authentication_shared_GreetingResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_dev_sultanov_grpc_authentication_shared_GreetingResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\025GreetingService.proto\022\'dev.sultanov.gr" +
                        "pc.authentication.shared\"\037\n\017GreetingRequ" +
                        "est\022\014\n\004name\030\001 \001(\t\"$\n\020GreetingResponse\022\020\n" +
                        "\010greeting\030\001 \001(\t2\222\001\n\017GreetingService\022\177\n\010g" +
                        "reeting\0228.dev.sultanov.grpc.authenticati" +
                        "on.shared.GreetingRequest\0329.dev.sultanov" +
                        ".grpc.authentication.shared.GreetingResp" +
                        "onseB\002P\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_dev_sultanov_grpc_authentication_shared_GreetingRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_sultanov_grpc_authentication_shared_GreetingRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_dev_sultanov_grpc_authentication_shared_GreetingRequest_descriptor,
                new java.lang.String[] { "Name", });
        internal_static_dev_sultanov_grpc_authentication_shared_GreetingResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_dev_sultanov_grpc_authentication_shared_GreetingResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_dev_sultanov_grpc_authentication_shared_GreetingResponse_descriptor,
                new java.lang.String[] { "Greeting", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
