// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

package dev.sultanov.grpc.authentication.shared;

public interface GreetingRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dev.sultanov.grpc.authentication.shared.GreetingRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
